rootProject.name = 'spring-boot-basics'
include 'chapter01-hello'
include 'chapter02-1-lombok'
include 'chapter02-2-di-ioc'
include 'chapter03-1-rest-api-basics'
include 'chapter03-2-thymeleaf'
include 'chapter03-3-mvc-model'
include 'chapter03-4-request-mapping'
include 'chapter04-1-validation'
include 'chapter04-2-config'
include 'chapter05-jpa'
include 'chapter06-jpa-relations'
include 'chapter07-security'
include 'chapter08-rest-client'
include 'chapter09-testing'
include 'chapter10-comprehensive'
