rootProject.name = 'spring-boot-basics'
include 'chapter01-hello'
include 'chapter02-lombok'
include 'chapter03-rest-api-basics'
include 'chapter03-2-thymeleaf'
include 'chapter04-validation'
include 'chapter05-jpa'
include 'chapter06-jpa-relations'
include 'chapter07-security'
include 'chapter08-rest-client'
include 'chapter09-testing'
include 'chapter10-comprehensive'
