rootProject.name = 'spring-boot-basics'
include 'chapter01-hello'
include 'chapter02-1-lombok'
include 'chapter02-2-di-ioc'
include 'chapter03-0-mvc-intro'
include 'chapter03-1-rest-api-basics'
include 'chapter03-2-thymeleaf'
include 'chapter03-3-mvc-model'
include 'chapter03-4-request-mapping'
include 'chapter03-5-file-upload'
include 'chapter03-6-thymeleaf-layout'
include 'chapter03-7-board-crud'
include 'chapter04-1-validation'
include 'chapter04-1-1-custom-validator'
include 'chapter04-2-config'
include 'chapter05-0-spring-data-jdbc'
include 'chapter05-1-jpa'
include 'chapter05-2-pagination-basic'
include 'chapter05-3-pagination-modern'
include 'chapter05-4-querydsl-search'
include 'chapter06-jpa-relations'
include 'chapter07-security'
include 'chapter07-2-security-form'
include 'chapter07-3-security-jwt'
include 'chapter07-4-security-oauth2'
include 'chapter07-5-security-firebase'
include 'chapter08-rest-client'
include 'chapter09-1-junit-basics'
include 'chapter09-testing'
include 'chapter10-comprehensive'
include 'chapter11-aop'
